PREFIX = /usr/local


all :
	cd src/ && $(MAKE)

clean :
      cd src/ && $(MAKE) clean

install : all
	install -d $(PREFIX)/include/urg_c/
	install -m 644 include/*.h $(PREFIX)/urg_c/
	install -d $(PREFIX)/lib/
	install -m 644 src/liburg_c.a $(PREFIX)/lib/
	install -d $(PREFIX)/bin/
	install -m 755 urg_c-config $(PREFIX)/bin/
