# Makefile for urgwidget

all :
	cd src/ && $(MAKE)
	cd samples/ && $(MAKE)

clean :
	cd src/ && $(MAKE) clean
	cd samples/ && $(MAKE) clean
	-cd viewers/ && $(MAKE) clean

.PHONY : all clean
######################################################################
