#!/bin/sh

version=1.0.0
prefix=/usr/local
includedir=${prefix}/urg_c
installlib=${prefix}/lib

usage="Usage: urg_c-config [--version] [--cflags] [--libs]"

if test $# -eq 0; then
      echo "${usage}" 1>&2
      exit 1
fi

while test $# -gt 0; do

  case $1 in
    --version)
      echo "${version}"
      ;;
    --cflags)
      echo -I${includedir}
      ;;
    --libs)
      echo ${installlib}
      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done
